kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:14
    commands:
      - npm install
      - npm run build

  - name: deploy
    pull: if-not-exists
    image: appleboy/drone-ssh
    settings:
      host: ssh_host
      username: root
      password:
        from_secret: ssh_passwd
      port: 22
      source:
        - "./dist"     # 指向构建输出的文件
      target: "/akmonitor/front/push"  # 目标服务器路径