kind: pipeline
type: docker
name: default

volumes:
  - name: cache
    host:
      path: /drone/cache

steps:
  - name: build
    image: node:22
    commands:
      - npm install
      - npm run build
      - cp -r ./dist /drone/cache/

  - name: deploy
    pull: if-not-exists
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username: root
      password:
        from_secret: ssh_passwd
      port: 22
      script: |
        rm -rf /drone/cache/dist
        cp -r /drone/cache/ .
#      source:
#        - "./dist"     # 指向构建输出的文件
#      target: "/akmonitor/front/push"  # 目标服务器路径
#      debug: true