kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:14
    commands:
      - npm install
      - npm run build

  - name: deploy
    image: appleboy/scp-action
    settings:
      host: 74.48.213.218
      username: root
      key:
        from_secret: baibing123
      port: 22
      source:
        - "build/*"     # 指向构建输出的文件
      target: "/akmonitor/front"  # 目标服务器路径