kind: pipeline
type: docker
name: default

volumes:
  - name: cache
    host:
      path: /drone/cache

steps:
  - name: build
    image: node:22
    depends_on: [clone]
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
      - name: web_build_dir
        path: /drone/src/dist
    commands:
      - npm install
      - npm run build
      - cp -r ./dist /cache

  - name: deploy
    pull: if-not-exists
    image: appleboy/drone-scp
    depends_on: [build]
    settings:
      host:
        from_secret: ssh_host
      username: root
      password:
        from_secret: ssh_passwd
      port: 22
      source:
        - ./dist     # 指向构建输出的文件
      target: /akmonitor/front/  # 目标服务器路径